### ISSUE TITLE
failed to start master

### ISSUE THREAD

**Issue by m3ngyang** [everpeace/kube-openmpi#19]
Hi, I came across the problem when running the demo.
```
➜  kube-openmpi git:(master) ✗ kubectl get po
NAME              READY     STATUS                  RESTARTS   AGE
mytest-master     0/2       Init:CrashLoopBackOff   7          12m
mytest-worker-0   1/1       Running                 0          4h
mytest-worker-1   1/1       Running                 0          4h
mytest-worker-2   1/1       Running                 0          4h
mytest-worker-3   1/1       Running                 0          4h
➜  kube-openmpi git:(master) ✗ kubectl logs mytest-master -c mpi-master
Error from server (BadRequest): container "mpi-master" in pod "mytest-master" is waiting to start: PodInitializing
➜  kube-openmpi git:(master) ✗ kubectl logs mytest-master -c hostfile-updater
Error from server (BadRequest): container "hostfile-updater" in pod "mytest-master" is waiting to start: PodInitializing
➜  kube-openmpi git:(master) ✗
```
How to solve the problem?

**Comment by everpeace** [comment]
@m3ngyang 

Hi, thanks for your interest to this project!

Your console tells it seemed that master couldn’t even start.  To dig the cause, would you mind sharing your `values.yaml` and the result of `kubectl describe my test-master`?

**Comment by m3ngyang** [comment]
I didn't change any value in the `values.yaml`

**Comment by m3ngyang** [comment]
Thx, I know the reason now. Because my cluster has been configured with RBAC, I didn't grant any authority to the default sa.

**Comment by everpeace** [comment]
@m3ngyang I'm glad to hear that.  If you found some issues or created some fixes, please feel free to contact me :-)

I'm now closing this issue.
